# Generated by Django 6.0 on 2025-12-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.CharField(max_length=50)),
                ('group_type', models.CharField(max_length=50)),
                ('group_details', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField()),
                ('preferred_cities', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('start_time', models.CharField(blank=True, max_length=20)),
                ('end_time', models.CharField(blank=True, max_length=20)),
                ('api_source', models.CharField(blank=True, max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips_app.trip')),
            ],
        ),
    ]
