# Generated by Django 6.0 on 2026-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
