import { useCallback, useEffect, useRef, useState } from 'react'
import { useLocation } from 'react-router-dom'

const INITIAL_FORM = {
  start_date: '',
  end_date: '',
  budget: 'moderate',
  group_type: 'couple',
  group_details: '',
  interests: '',
  preferred_cities: '',
}

const NEW_ITEM = {
  day_number: '',
  title: '',
  category: 'morning',
  description: '',
  location: '',
  image_url: '',
  start_time: '',
  end_time: '',
}

const API_BASE = 'http://127.0.0.1:8000/trips'

function toList(value) {
  if (!value) return []
  if (Array.isArray(value)) return value
  return value
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean)
}

function cleanseTripPayload(payload) {
  return {
    ...payload,
    interests: toList(payload.interests),
    preferred_cities: toList(payload.preferred_cities),
  }
}

function cleanseItemPayload(item) {
  return {
    day_number: Number(item.day_number),
    title: item.title,
    category: item.category,
    description: item.description || '',
    location: item.location || '',
    image_url: item.image_url || '',
    start_time: item.start_time || '',
    end_time: item.end_time || '',
  }
}

export default function ItineraryPage() {
  const location = useLocation()
  const incoming = location.state?.tripParams
  const [form, setForm] = useState(() => ({ ...INITIAL_FORM, ...incoming }))
  const [trip, setTrip] = useState(null)
  const [items, setItems] = useState([])
  const [status, setStatus] = useState('idle')
  const [error, setError] = useState(null)
  const [message, setMessage] = useState('')
  const [newItem, setNewItem] = useState(NEW_ITEM)
  const autoGenerated = useRef(false)

  useEffect(() => {
    if (incoming) {
      setForm((prev) => ({ ...prev, ...incoming }))
    }
  }, [incoming])

  const handleGenerate = useCallback(
    async (payloadOverride) => {
      const payload = cleanseTripPayload(payloadOverride ?? form)
      setStatus('loading')
      setError(null)
      setMessage('')

      try {
        const response = await fetch(`${API_BASE}/generate/`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include',
          body: JSON.stringify(payload),
        })

        if (!response.ok) {
          throw new Error('Unable to generate itinerary. Please try again.')
        }

        const data = await response.json()
        setTrip(data)
        setItems(data.items || [])
        setStatus('success')
        setMessage('Itinerary generated successfully.')
      } catch (err) {
        console.error('Trip generation failed', err)
        setError(err.message)
        setStatus('error')
      }
    },
    [form],
  )

  useEffect(() => {
    if (!autoGenerated.current && location.state?.autoGenerate && incoming) {
      autoGenerated.current = true
      handleGenerate(incoming)
    }
  }, [handleGenerate, incoming, location.state])

  function handleFormChange(event) {
    const { name, value } = event.target
    setForm((prev) => ({ ...prev, [name]: value }))
  }

  function handleItemFieldChange(itemId, field, value) {
    setItems((prev) => prev.map((item) => (item.id === itemId ? { ...item, [field]: value } : item)))
  }

  function handleNewItemChange(event) {
    const { name, value } = event.target
    setNewItem((prev) => ({ ...prev, [name]: value }))
  }

  async function createItem(event) {
    event.preventDefault()
    if (!trip) return
    setMessage('')

    try {
      const response = await fetch(`${API_BASE}/${trip.id}/items/`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify(cleanseItemPayload(newItem)),
      })

      if (!response.ok) {
        throw new Error('Unable to create itinerary item.')
      }

      const data = await response.json()
      setItems((prev) => [...prev, data])
      setNewItem(NEW_ITEM)
      setMessage('Itinerary item added.')
    } catch (err) {
      console.error('Create item failed', err)
      setError(err.message)
    }
  }

  async function updateItem(itemId) {
    if (!trip) return
    setMessage('')
    const current = items.find((item) => item.id === itemId)
    if (!current) return

    try {
      const response = await fetch(`${API_BASE}/${trip.id}/items/${itemId}/`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify(cleanseItemPayload(current)),
      })

      if (!response.ok) {
        throw new Error('Unable to update itinerary item.')
      }

      const data = await response.json()
      setItems((prev) => prev.map((item) => (item.id === itemId ? data : item)))
      setMessage('Itinerary item updated.')
    } catch (err) {
      console.error('Update item failed', err)
      setError(err.message)
    }
  }

  async function deleteItem(itemId) {
    if (!trip) return
    setMessage('')

    try {
      const response = await fetch(`${API_BASE}/${trip.id}/items/${itemId}/`, {
        method: 'DELETE',
        credentials: 'include',
      })

      if (!response.ok) {
        throw new Error('Unable to delete itinerary item.')
      }

      setItems((prev) => prev.filter((item) => item.id !== itemId))
      setMessage('Itinerary item removed.')
    } catch (err) {
      console.error('Delete item failed', err)
      setError(err.message)
    }
  }

  return (
    <section className="container py-4">
      <h1 className="mb-3 text-center">Itinerary Planner</h1>
      <p className="text-muted text-center">Update your preferences and refine each itinerary item.</p>

      <form
        className="row g-3 mb-4"
        onSubmit={(event) => {
          event.preventDefault()
          handleGenerate()
        }}
      >
        <div className="col-md-6">
          <label className="form-label" htmlFor="start_date">
            Start Date
          </label>
          <input id="start_date" name="start_date" type="date" className="form-control" value={form.start_date} onChange={handleFormChange} required />
        </div>

        <div className="col-md-6">
          <label className="form-label" htmlFor="end_date">
            End Date
          </label>
          <input id="end_date" name="end_date" type="date" className="form-control" value={form.end_date} onChange={handleFormChange} required />
        </div>

        <div className="col-md-4">
          <label className="form-label" htmlFor="budget">
            Budget
          </label>
          <select id="budget" name="budget" className="form-select" value={form.budget} onChange={handleFormChange}>
            <option value="budget">Budget</option>
            <option value="moderate">Moderate</option>
            <option value="luxury">Luxury</option>
          </select>
        </div>

        <div className="col-md-4">
          <label className="form-label" htmlFor="group_type">
            Group Type
          </label>
          <select id="group_type" name="group_type" className="form-select" value={form.group_type} onChange={handleFormChange}>
            <option value="solo">Solo</option>
            <option value="couple">Couple</option>
            <option value="family">Family</option>
            <option value="friends">Friends</option>
          </select>
        </div>

        <div className="col-md-4">
          <label className="form-label" htmlFor="group_details">
            Group Details
          </label>
          <input
            id="group_details"
            name="group_details"
            type="text"
            className="form-control"
            placeholder="e.g. romantic getaway"
            value={form.group_details}
            onChange={handleFormChange}
          />
        </div>

        <div className="col-12">
          <label className="form-label" htmlFor="interests">
            Interests (comma separated)
          </label>
          <input
            id="interests"
            name="interests"
            type="text"
            className="form-control"
            placeholder="food, anime, temples"
            value={form.interests}
            onChange={handleFormChange}
          />
        </div>

        <div className="col-12">
          <label className="form-label" htmlFor="preferred_cities">
            Preferred Cities (comma separated)
          </label>
          <input
            id="preferred_cities"
            name="preferred_cities"
            type="text"
            className="form-control"
            placeholder="Tokyo, Kyoto, Osaka"
            value={form.preferred_cities}
            onChange={handleFormChange}
          />
        </div>

        <div className="col-12 text-center">
          <button className="btn btn-dark px-4" type="submit" disabled={status === 'loading'}>
            {status === 'loading' ? 'Generating…' : 'Generate Itinerary'}
          </button>
        </div>
      </form>

      {error && <div className="alert alert-danger">{error}</div>}
      {message && <div className="alert alert-success">{message}</div>}

      {trip ? (
        <>
          <div className="mb-4">
            <h2 className="h4">Current itinerary</h2>
            <p className="text-muted">Fine-tune each activity below.</p>

            <div className="d-flex flex-column gap-3">
              {items.map((item) => (
                <div className="card" key={item.id}>
                  <div className="card-body">
                    <div className="row g-2">
                      <div className="col-sm-2">
                        <label className="form-label">Day</label>
                        <input
                          type="number"
                          className="form-control"
                          value={item.day_number}
                          onChange={(event) => handleItemFieldChange(item.id, 'day_number', event.target.value)}
                        />
                      </div>
                      <div className="col-sm-4">
                        <label className="form-label">Title</label>
                        <input
                          type="text"
                          className="form-control"
                          value={item.title}
                          onChange={(event) => handleItemFieldChange(item.id, 'title', event.target.value)}
                        />
                      </div>
                      <div className="col-sm-3">
                        <label className="form-label">Category</label>
                        <select
                          className="form-select"
                          value={item.category}
                          onChange={(event) => handleItemFieldChange(item.id, 'category', event.target.value)}
                        >
                          <option value="morning">Morning</option>
                          <option value="afternoon">Afternoon</option>
                          <option value="evening">Evening</option>
                          <option value="local">Local</option>
                          <option value="iconic">Iconic</option>
                          <option value="unique">Unique</option>
                        </select>
                      </div>
                      <div className="col-sm-3">
                        <label className="form-label">Location</label>
                        <input
                          type="text"
                          className="form-control"
                          value={item.location}
                          onChange={(event) => handleItemFieldChange(item.id, 'location', event.target.value)}
                        />
                      </div>
                      <div className="col-12">
                        <label className="form-label">Description</label>
                        <textarea
                          className="form-control"
                          rows="2"
                          value={item.description}
                          onChange={(event) => handleItemFieldChange(item.id, 'description', event.target.value)}
                        />
                      </div>
                      <div className="col-sm-3">
                        <label className="form-label">Start Time</label>
                        <input
                          type="text"
                          className="form-control"
                          value={item.start_time}
                          onChange={(event) => handleItemFieldChange(item.id, 'start_time', event.target.value)}
                        />
                      </div>
                      <div className="col-sm-3">
                        <label className="form-label">End Time</label>
                        <input
                          type="text"
                          className="form-control"
                          value={item.end_time}
                          onChange={(event) => handleItemFieldChange(item.id, 'end_time', event.target.value)}
                        />
                      </div>
                    </div>
                    <div className="d-flex justify-content-end gap-2 mt-3">
                      <button type="button" className="btn btn-outline-secondary" onClick={() => updateItem(item.id)}>
                        Save
                      </button>
                      <button type="button" className="btn btn-danger" onClick={() => deleteItem(item.id)}>
                        Delete
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <div className="card-body">
              <h3 className="h5 mb-3">Add a new item</h3>
              <form className="row g-2" onSubmit={createItem}>
                <div className="col-sm-2">
                  <label className="form-label">Day</label>
                  <input type="number" name="day_number" className="form-control" value={newItem.day_number} onChange={handleNewItemChange} required />
                </div>
                <div className="col-sm-4">
                  <label className="form-label">Title</label>
                  <input type="text" name="title" className="form-control" value={newItem.title} onChange={handleNewItemChange} required />
                </div>
                <div className="col-sm-3">
                  <label className="form-label">Category</label>
                  <select name="category" className="form-select" value={newItem.category} onChange={handleNewItemChange}>
                    <option value="morning">Morning</option>
                    <option value="afternoon">Afternoon</option>
                    <option value="evening">Evening</option>
                    <option value="local">Local</option>
                    <option value="iconic">Iconic</option>
                    <option value="unique">Unique</option>
                  </select>
                </div>
                <div className="col-sm-3">
                  <label className="form-label">Location</label>
                  <input type="text" name="location" className="form-control" value={newItem.location} onChange={handleNewItemChange} />
                </div>
                <div className="col-12">
                  <label className="form-label">Description</label>
                  <textarea name="description" className="form-control" rows="2" value={newItem.description} onChange={handleNewItemChange} />
                </div>
                <div className="col-sm-3">
                  <label className="form-label">Start Time</label>
                  <input type="text" name="start_time" className="form-control" value={newItem.start_time} onChange={handleNewItemChange} />
                </div>
                <div className="col-sm-3">
                  <label className="form-label">End Time</label>
                  <input type="text" name="end_time" className="form-control" value={newItem.end_time} onChange={handleNewItemChange} />
                </div>
                <div className="col-sm-6">
                  <label className="form-label">Image URL</label>
                  <input type="text" name="image_url" className="form-control" value={newItem.image_url} onChange={handleNewItemChange} />
                </div>
                <div className="col-12 text-end">
                  <button type="submit" className="btn btn-primary">
                    Add Item
                  </button>
                </div>
              </form>
            </div>
          </div>
        </>
      ) : (
        <p className="text-center text-muted mt-5">Generate an itinerary to see recommended activities.</p>
      )}
    </section>
  )
}
